import type { Metadata } from "next";
import { Baskervville } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const baskerville = Baskervville({
  variable: "--font-baskerville",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

const baskervilleOldFace = localFont({
  src: "./BASKVILL.ttf",
  variable: "--font-baskerville-old-face",
  display: "swap",
});

const baskervilleClassic = localFont({
  src: "./Baskerville-01.ttf",
  variable: "--font-baskervilleClassic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baskerville.variable} ${baskervilleOldFace.variable} ${baskervilleClassic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
