import type { Metadata } from "next";
import { Baskervville } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import LLNav from "@/components/LLNav";
import { client } from "@/lib/sanity/client";
import { issuesQuery, articlesQuery, seriesQuery } from "@/lib/sanity/queries";
import { IssuesProvider } from "@/lib/contexts/IssuesContext";
import { ArticlesProvider } from "@/lib/contexts/ArticlesContext";
import type { Issue } from "@/lib/contexts/IssuesContext";
import type { Article, Series } from "@/lib/contexts/ArticlesContext";

export const revalidate = 3600;

const baskerville = Baskervville({
  variable: "--font-baskerville",
  display: "swap",
  weight: "400",
  subsets: ["latin"],
});

const baskervilleOldFace = localFont({
  src: "./BASKVILL.ttf",
  variable: "--font-baskerville-old-face",
  display: "swap",
});

const baskervilleClassic = localFont({
  src: "./Baskerville-01.ttf",
  variable: "--font-baskervilleClassic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let issues: Issue[] = [];
  let articles: Article[] = [];
  let series: Series[] = [];

  try {
    [issues, articles, series] = await Promise.all([
      client.fetch(issuesQuery),
      client.fetch(articlesQuery),
      client.fetch(seriesQuery),
    ]);
  } catch {
    // Sanity not yet configured
  }

  return (
    <html lang="en">
      <body
        className={`${baskerville.variable} ${baskervilleOldFace.variable} ${baskervilleClassic.variable} antialiased`}
      >
        <IssuesProvider issues={issues}>
          <ArticlesProvider articles={articles} series={series}>
            <LLNav />
            {children}
          </ArticlesProvider>
        </IssuesProvider>
      </body>
    </html>
  );
}
